AllCops:
  TargetRubyVersion: 2.4

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SoleNestedConditional:
  AllowModifier: true

Metrics/AbcSize:
  Max: 22

CyclomaticComplexity:
  Max: 9
